discovery:
    address:
        ip: 127.0.0.1
        port: 8080
        complete: ${discovery.address.ip}:${discovery.address.port}
    cluster:
        size: 2
    distribution:
        type: atomix
    redis:
        address: 127.0.0.1:6379
    atomix:
        name: ${discovery.address.complete}
        members: ${discovery.address.ip}:8080, ${discovery.address.ip}:8081, ${discovery.address.ip}:8082
server:
    port: 8090
    address: 127.0.0.1
spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
    application:
        name: discovery-client